### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by nickjmeyer** [ludwigpacifici/modern-cpp-font-lock#9] opened 2017-02-17 15:10 UTC
Highlighting template parameters have been one thing that have never worked consistently for me in emacs.  I tried installing `modern-cpp-font-lock`, but I'm still getting the following hightlighting:

![image](https://cloud.githubusercontent.com/assets/9648755/23070507/3e65a850-f4f9-11e6-900f-26ea4ab0f340.png)

The template paramters `Features` and `Model` are not hightlighted, but above `State` is.

Any ideas for how to fix this?

**Comment by ludwigpacifici** [comment] 2017-02-20 08:59
I can reproduce your issue with `emacs -Q`:

![tmp11](https://cloud.githubusercontent.com/assets/923945/23117724/f62b7144-f748-11e6-9709-8191a3908515.png)

If I erase '>' and write it again the font lock (from `c++-mode`) gets refreshed and displays it nicely:

![tmp12](https://cloud.githubusercontent.com/assets/923945/23117741/07c5ebf0-f749-11e6-84ee-ff8c7cd58b2f.png)

However, modern-cpp-font-lock aims to highlight C++ keywords (`int`, `auto`, `nullptr`, etc.). The code parsing, and extra font lock is done by `c++-mode`. If you want to see only the effect of modern-cpp-font-lock, use `M-x text-mode` and `M-x modern-c++-font-lock-mode`:

![tmp13](https://cloud.githubusercontent.com/assets/923945/23117902/cea204de-f749-11e6-80a2-3be588c6efd5.png)

The best solution, is to fix the issue in the right place which is [`c++-mode`](http://cc-mode.sourceforge.net/). If you wish, I can report for you this issue to the maintainer?

**Comment by nickjmeyer** [comment] 2017-02-20 14:47
Ah, gotcha.  Thanks for investigating this!  If you wouldn't mind submittng a report that'd be great.  I've never submitted an official bug report, so might be nice to see what it looks like.  Could you place the link to the bug report submission in this thread for reference?  That way I can follow the status of it.

(Also, I did find something else that does seem to be a `modern-cpp-font-lock` issue.  It's a separate thing so I'll make another post.)

**Comment by ludwigpacifici** [comment] 2017-02-21 17:27
[Link to the cc-mode issue](https://sourceforge.net/p/cc-mode/mailman/message/35679907/). Feel free to jump in the thread.

**Comment by nickjmeyer** [comment] 2017-02-21 21:18
This is great.  I really appreciate you taking the time to do that.  I read through the post and will be curious to see what the maintainer has to say!

**Comment by ludwigpacifici** [comment] 2017-03-27 07:08
FYI, reply from Alan Mackenzie: https://sourceforge.net/p/cc-mode/mailman/message/35750252/

**Comment by nickjmeyer** [comment] 2017-03-27 14:46
Ah, good to know!

**Comment by ludwigpacifici** [comment] 2017-04-06 09:42
A patch from Alan Mackenzie is available for your issue: https://sourceforge.net/p/cc-mode/mailman/message/35771591/

I will do some tests. That would be great if you can do some on your side as well.

**Comment by nickjmeyer** [comment] 2017-04-09 11:03
Doing this now.  Should we be writing actual test cases or simply checking
code snippets?

**Comment by ludwigpacifici** [comment] 2017-04-09 12:26
Test it on the code where you saw the error. For example, the snippet in your first post. Ii understand it is manual tests - I am not aware of testing framework in the `cc-mode`.

I will do some checks as well. Do you agree with the Fix of Alan?

**Comment by nickjmeyer** [comment] 2017-04-09 13:52
I tried to apply the patch using the `apply` utility, but it rejected 2/3 of the chunks.  I tried to figure out the discrepancy by hand.  It seemed to work (i.e., compile and run).

I checked any files I can remember where I ran into this issue and it seems to be fixed.  I did send Alan a PM to see which version of `cc-mode` the patch should be applied to as it didn't apply directly, so I'm assuming hes testing a different version.

**Comment by ludwigpacifici** [comment] 2017-04-09 14:20
To apply a patch try:

    $ patch --dry-run < filename.diff

If no errors, then apply the patch with

    $ patch < filename.diff

Let me know if Alan suggests you a specific branch to apply the patch. I am interested to know.I have a limited access to the Internet since I moved recently. I will try the patch tomorrow.

**Comment by nickjmeyer** [comment] 2017-04-09 14:31
To apply the patch I did `patch -p1 < filename.diff` and I get the output:
```
patching file cc-engine.el
Hunk #1 succeeded at 6005 with fuzz 2.
Hunk #2 FAILED at 6972.
Hunk #3 FAILED at 6988.
2 out of 3 hunks FAILED -- saving rejects to file cc-engine.el.rej
patching file cc-mode.el
```

The file `cc-engine.el.rej` looks like:
```diff
***************
*** 6965,6970 ****
  	 ;; This function might do hidden buffer changes.
  
  	 (let ((start (point))
  	;; If `c-record-type-identifiers' is set then activate
  	;; recording of any found types that constitute an argument in
  	;; the arglist.
--- 6972,6978 ----
  	 ;; This function might do hidden buffer changes.
  
  	 (let ((start (point))
+ 	(old-found-types (c-copy-found-types))
  	;; If `c-record-type-identifiers' is set then activate
  	;; recording of any found types that constitute an argument in
  	;; the arglist.
***************
*** 6980,6985 ****
  		  (nconc c-record-found-types c-record-type-identifiers)))
  	  t)
  
  			 (goto-char start)
  			 nil)))
  
--- 6988,6994 ----
  		  (nconc c-record-found-types c-record-type-identifiers)))
  	  t)
  
+       (setq c-found-types old-found-types)
  			 (goto-char start)
  			 nil)))
  

```

I'm pretty sure I was able to figure out which lines needed to be edited to apply the patch.  Though I figured it would be best to test the version he is working on.

**Comment by ludwigpacifici** [comment] 2017-07-14 20:25
Hello @nickjmeyer 

I will close this issue as it is not related to this project. Alan, [commited a partial fix](https://sourceforge.net/p/cc-mode/mailman/message/35943884/). If you use GNU Emacs 26, you'll get a better highlight. I thank you for your bug report. If you see another issue, do not hesitate to raise a bug here or directly to [cc-mode](http://cc-mode.sourceforge.net/).

**Closed as completed by ludwigpacifici** 2017-07-14 20:25 UTC
