### ISSUE TITLE
Support for digit separators?

### ISSUE THREAD

**Issue by preetpalS** [ludwigpacifici/modern-cpp-font-lock#5] opened 2016-06-22 00:25 UTC
Are there plans to support to support digit separators in this library? C++14 supports using single quotes as [digit separators](https://en.wikipedia.org/wiki/C%2B%2B14#Digit_separators) but this messes up the font-locking quite badly when using the default C++ mode or this library.

**Comment by ludwigpacifici** [comment] 2016-06-22 08:57
Hello @preetpalS 

Single quotes as digit separator are supported however, the issue might be due to `c++-mode`. To make sure of this:

<kbd>M-x</kbd> `text-mode` <kbd>[RET]</kbd> then <kbd>M-x</kbd> `modern-c++-mode-font-lock-mode` <kbd>[RET]</kbd>

From you link, only pre/postfix integers will be highlighted:

```
auto integer_literal = 1'000'000; // no highlight on 1'000'000
auto binary_literal = 0b0100'1100'0110; // highlight {0b} and {0100'1100'0110}
```

However, when `c++-mode` is activated, my highlighting occurs after the major mode. Few days ago, I sent an [email](https://sourceforge.net/p/cc-mode/mailman/message/35142472/) to the maintainer of `cc-mode` to fix this issue. A fix should be soon available for the major-mode.

I'll have a look if I can prioritize the syntax highlighting to solve this issue.

**Comment by preetpalS** [comment] 2016-06-22 23:19
Upon following your advice, I found that the issue I was experiencing was due to `c++-mode` also being activated (but `c++-mode` cannot really be deactivated when writing C++ as it is needed for indentation).

Thanks for pursuing this issue and for raising it with the maintainer of `cc-mode` as well.

**Comment by ludwigpacifici** [comment] 2016-10-04 13:03
Hello @preetpalS 

The issue is due to the syntax table. The `c++-mode` syntax table define quote as a "string word". Check it with `C-h s`. The syntax table is run first to highlight words, then the minor mode is called afterwards. Unfortunately, the highlight in the digit is already done, I cannot revert from the minor mode.

I will close this issue as I do not have a solution for this. If you have one feel free to ask a pull request.

Thanks

**Closed as completed by ludwigpacifici** 2016-10-04 13:03 UTC
